### PR TITLE
Add feature for getting the closest good spec.

### PR DESCRIPTION
**Pull request by harshithamenon**

### CODE REVIEW

**Comment by harshithamenon** [comment]
Hey @vsoch This has a function that shows how we have to scale the features of the error spec based on the cluster it is assigned to and then use that weighted feature to find the closest good spec. You can replace that part with KNN.

**Comment by vsoch** [comment]
oh perfect! So just so I understand - I can use this to find the closest good spec in the UI (scoped to maybe just one error cluster). And the "replace with KNN" part = you don't mean now, but sometime in the future when/if we production-ize this?

And sorry about the typo in the other script, thank you for fixing it!

**Comment by harshithamenon** [comment]
> oh perfect! So just so I understand - I can use this to find the closest good spec in the UI (scoped to maybe just one error cluster). And the "replace with KNN" part = you don't mean now, but sometime in the future when/if we production-ize this?
> 
Yes, you can use this to find the closest good spec for a given error spec for your UI. You can call the function find_nearest_good_spec(uid, cluster_id_of_uid) to get the spec hash and a score. I just return the top one but one can sort the scores and return top k. 
You can use KNN whenever you think is a good time to switch. 

> And sorry about the typo in the other script, thank you for fixing it!

No problem at all.

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
Also I noticed your code is really nice and organized / commented here, thank you <3

**Comment by harshithamenon** [comment]
Nice of you to comment that <3. 
Yesterday I was too swamped with a proposal submission, but today I had more time :). I felt terrible that you had to go through all that trouble to restructure and comment my code — sorry about that.

**Pull request merged**
